### ISSUE TITLE
Error to observe changes in "maintenanceNeeded" property in smart-coffee-machine-client.js 

### ISSUE THREAD

**Issue by lbruno-github** [eclipse/thingweb.node-wot#764]
I am professor of a Web of Things Course and give lectures to students about W3C WoT Architecture. They are using the thingweb project to implement a IoT prototype in Web technology. 
 
The example of the coffe machine is very important to explore the different concepts of the WoT Scripting API. We are facing a problem to observe the changes of the "maintenanceNeeded" property. When the client script is running it halts in this asynchronous operation (thing.observeProperty("maintenanceNeeded", async (data)) and system return the following error:

[core/servient] Servient caught Asynchronous script error 'C:\Users\Utilizador\Documents\Desenvolvimentos\Web_Coisas\thingweb.node-wot-master\examples\scripts\smart-coffee-machine-client.js' and halted with Error: Client error: Not Found
    at HttpClient.checkFetchResponse (C:\Users\Utilizador\Documents\Desenvolvimentos\Web_Coisas\thingweb.node-wot-master\packages\binding-http\dist\http-client.js:283:19)
    at LongPollingSubscription.<anonymous> (C:\Users\Utilizador\Documents\Desenvolvimentos\Web_Coisas\thingweb.node-wot-master\packages\binding-http\dist\subscription-protocols.js:42:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Utilizador\Documents\Desenvolvimentos\Web_Coisas\thingweb.node-wot-master\packages\binding-http\dist\subscription-protocols.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Do you have the same error? Is it problem of the http-client or http-server of the "binding http"?
The problem is persistent in Windows and Raspberry Pi Debian] operating systems.
Someone can help us in this issue? Thanks in advance!

**Comment by danielpeintner** [comment]
I did the following and can reproduce the issue. 
1. Start [smart-coffee-machine.js](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/smart-coffee-machine.js) server in a command shell
 `node packages\cli\dist\cli.js examples\scripts\smart-coffee-machine.js`
2. Start [smart-coffee-machine-client.js](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/smart-coffee-machine-client.js) client in another command shell
  `node packages\cli\dist\cli.js --clientonly examples\scripts\smart-coffee-machine-client.js`

Let us take a closer look.

**Comment by danielpeintner** [comment]
The issue is that for op `observeproperty` it reaches out to

http://localhost:8080/smart-coffee-machine/properties/maintenanceNeeded/observable (reports 404)

while in the case of HTTP and long-polling it should just use

http://localhost:8080/smart-coffee-machine/properties/maintenanceNeeded

@relu91 do you know whether there is any rationale to keep those 2 lines?

https://github.com/eclipse/thingweb.node-wot/blob/38eff6d5aece1f4630398d31a1a4a7ed81f78d5e/packages/binding-http/src/http-server.ts#L355-L356

**Comment by lbruno-github** [comment]
I commented these two lines and the client no longer halts as before.
However, I think he doesn't detect (or receives this notification) in client the value changes of the variable because he continuously writes the same message: 
maintenanceNeeded property has changed! New value is:
[Function: value]

What to do in this case?

**Comment by danielpeintner** [comment]
Note: I am still investing but I am a pit puzzled why long polling causes issues. Maybe @relu91 has time to look into since he wrote this part of the code.

I also wonder why there is no return after Line 745 like it is done in the other GET branch

https://github.com/eclipse/thingweb.node-wot/blob/38eff6d5aece1f4630398d31a1a4a7ed81f78d5e/packages/binding-http/src/http-server.ts#L745

**Comment by relu91** [comment]
>I also wonder why there is no return after Line 745 like it is done in the other GET branch

Oh yeah it seems that somehow the return was removed, but without it the code skip to the end of the function where:

https://github.com/eclipse/thingweb.node-wot/blob/38eff6d5aece1f4630398d31a1a4a7ed81f78d5e/packages/binding-http/src/http-server.ts#L914

That's why is returning 404. I'm not 100% sure but I think adding the return there should fix the issue.

**Comment by danielpeintner** [comment]
The error is gone with adding `return`

@lbruno-github can you check also (see https://github.com/eclipse/thingweb.node-wot/pull/775)

**Comment by lbruno-github** [comment]
Thanks for your help!
Effectivley the 404 error doesn't occur with the addition of the "return" statement.
But, after this correction, in the coffee machine client  it is still not returning back the change to the "MaintenanceNeeded" property value that is being observed. 
Is it a problem in the description of the property in Thing Description or from the code that manages the observe pattern?

**Comment by danielpeintner** [comment]
The process has changed between node-wot version `0.7.x` and `0.8.x` (see also https://w3c.github.io/wot-scripting-api/#dom-exposedthing-emitpropertychange).
Having said, I think observing properties is not fully supported yet.

see
https://github.com/eclipse/thingweb.node-wot/blob/efc647961038cddbfb677b7573af680ae212514d/packages/core/src/exposed-thing.ts#L197

Let me try to look into. I cannot say how long it takes.
